print("Before loads")
source("WGCNA_sim_utils.R")
print("sim utils ok")
source("WGCNA_clust_utils.R")
print("clust utils ok")
source("WGCNA_diagnostics.R")
print("diagnostics ok")
source("WGCNA_sim_tests.R")
print("tests ok")
